### ISSUE TITLE
编译报错，找不到v100工作集 

### ISSUE THREAD

**Issue by AvatarGuo** [79134054/VSEngine2#3]
![image](https://user-images.githubusercontent.com/17995601/181659301-14368925-5aed-400d-b3d3-742790af94ca.png)
https://www.cnblogs.com/mq0036/p/15118121.html

如题 这个怎么解决啊，卡了两天了。升级到2019也是报错
![image](https://user-images.githubusercontent.com/17995601/181659453-471584fe-9dee-4480-8d94-d40ba071dc2a.png)

看你升级了2017， 我好像下的是2-1版本

**Comment by 79134054** [comment]
你vs2019装的有问题，不用先用2010打开



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月29日(周五) 上午8:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [79134054/VSEngine2] 编译报错，找不到v100工作集  (Issue #3)




 

 https://www.cnblogs.com/mq0036/p/15118121.html
 
如题 这个怎么解决啊，卡了两天了。升级到2019也是报错

**Comment by AvatarGuo** [comment]
https://blog.csdn.net/qq_41601836/article/details/105352861 按照这个方法修改了下VS就好了
